<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Phalcon Tutorial</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <?php
        echo "<h1>Hello!</h1>";
        echo $this->tag->linkTo(["user/signup", "Sign Up Here!", 'class' => 'btn btn-primary']);
    ?>
</div>
</body>
</html>