<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<h2>Sign up using this form</h2>

<?php echo $this->tag->form("user/signup"); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textField("username"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="password">Password</label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Register"); ?><br>
    </p>
    <p>
        <?php echo $message; ?>
    </p>
</form>

<?php
echo $this->tag->linkTo(["user/login", "Login Here!", 'class' => 'btn btn-primary']);
?>

</body>
</html>